/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Sound.SoundPlayer;
import Logic.GameInitialize;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *<h2>Class that creates a window dialog.</h2> When you click on the close button of the {@linkplain CharacterFrame} window.<br>
 *This window purpose is to keep the user in the game by popping close confirmation window.
 * @author Rima Ryskin
 * @author Bogdan Kirylyuk
 */
public class ExitShopDialog extends javax.swing.JDialog
{
	/**
	 * Holds reference to the parent window (character frame).
	 */
    private CharacterFrame parent;
    /**
     * The constructor of the class initializes the components of this window.
     * @param parent receives instance of {@linkplain CharacterFrame} that refers to the window this method called from.
     * @param modal receives boolean variable that defines whether this window will be modal or not.
     */
    public ExitShopDialog(CharacterFrame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        SoundPlayer.Play("Ding");
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.parent = parent;
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        sureToExitText = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(GameInitialize.gameVersion);
        setAlwaysOnTop(true);
        setFocusableWindowState(false);
        setIconImage(new ImageIcon(getClass().getResource("fistIcon.png")).getImage()
        );
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        sureToExitText.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        sureToExitText.setForeground(new java.awt.Color(255, 255, 255));
        sureToExitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sureToExitText.setText("<html>Are you sure you want to quit?<br>\nAll progress gained will be lost!\n</html>");
        sureToExitText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        yesButton.setBackground(java.awt.Color.lightGray);
        yesButton.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        yesButton.setText("I'm a quitter...");
        yesButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setBackground(java.awt.Color.lightGray);
        noButton.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        noButton.setText("Hell no!");
        noButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sureToExitText, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sureToExitText, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yesButtonActionPerformed
    {//GEN-HEADEREND:event_yesButtonActionPerformed
        
        parent.disposeConfirmed();
        new MainMenu(false);
        this.dispose();
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noButtonActionPerformed
    {//GEN-HEADEREND:event_noButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_noButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noButton;
    private javax.swing.JLabel sureToExitText;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
