/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Logic.InteractionWithDB;
import Logic.TableRow;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author dima
 */
public class HighScoreStatsFrame extends javax.swing.JFrame
{

    /**
     * Creates new form HighScoreStatsFrame
     */
    public HighScoreStatsFrame(String playerLogin)
    {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        populateTable(weekWinTable, true, true);
        populateTable(weekLoseTable, false, true);
        populateTable(generalWinTable, true, false);
        populateTable(generalLoseTable, false, false);
        
        populateUserStats(playerLogin, userWeekWinsCounterLabel, true, true);
        populateUserStats(playerLogin, userWeekLossesCounterLabel, false, true);
        populateUserStats(playerLogin, userEverWinsCounterLabel, true, false);
        populateUserStats(playerLogin, userEverLossesCounterLabel, false, false);
    }
    
    private void populateTable(JTable table, boolean isWin, boolean isRecent)
    {
        
        int tableCol = 0;
        
        try
        {
            List tableData = new InteractionWithDB().getAllScore(isWin, isRecent);
            for (int tableRow = 0 ; tableRow < tableData.size() ; tableRow++)
            {
                String username = ((TableRow) tableData.get(tableRow)).username;
                int amount = ((TableRow) tableData.get(tableRow)).amount;
                
                table.setValueAt(username, tableRow, 0);
                table.setValueAt(amount, tableRow, 1);
            }
        } catch (CommunicationsException ex)
        {
            Logger.getLogger(HighScoreStatsFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex)
        {
            Logger.getLogger(HighScoreStatsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void populateUserStats(String playerLogin, JLabel label, boolean isWin, boolean isRecent)
    {
        try
        {
            label.setText(
                    Integer.toString(new InteractionWithDB().getUserState(playerLogin, isWin, isRecent))
            );
        } catch (CommunicationsException ex)
        {
            Logger.getLogger(HighScoreStatsFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex)
        {
            Logger.getLogger(HighScoreStatsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        weekWinTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        weekLoseTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        generalWinTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        generalLoseTable = new javax.swing.JTable();
        thisWeekLabel = new javax.swing.JLabel();
        topHallLabel = new javax.swing.JLabel();
        allTimeLabel = new javax.swing.JLabel();
        winsLabel = new javax.swing.JLabel();
        lossesLabel = new javax.swing.JLabel();
        youLabel1 = new javax.swing.JLabel();
        userWeekWinsCounterLabel = new javax.swing.JLabel();
        userWeekLossesCounterLabel = new javax.swing.JLabel();
        userEverWinsCounterLabel = new javax.swing.JLabel();
        youLabel2 = new javax.swing.JLabel();
        userEverLossesCounterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setFocusTraversalPolicyProvider(true);
        setForeground(java.awt.Color.black);
        setResizable(false);

        weekWinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "User", "Score"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        weekWinTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(weekWinTable);
        if (weekWinTable.getColumnModel().getColumnCount() > 0)
        {
            weekWinTable.getColumnModel().getColumn(0).setResizable(false);
            weekWinTable.getColumnModel().getColumn(1).setResizable(false);
        }

        weekLoseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "User", "Score"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        weekLoseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(weekLoseTable);
        if (weekLoseTable.getColumnModel().getColumnCount() > 0)
        {
            weekLoseTable.getColumnModel().getColumn(0).setResizable(false);
            weekLoseTable.getColumnModel().getColumn(1).setResizable(false);
        }

        generalWinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "User", "Score"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        generalWinTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(generalWinTable);
        if (generalWinTable.getColumnModel().getColumnCount() > 0)
        {
            generalWinTable.getColumnModel().getColumn(0).setResizable(false);
            generalWinTable.getColumnModel().getColumn(1).setResizable(false);
        }

        generalLoseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "User", "Score"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        generalLoseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(generalLoseTable);
        if (generalLoseTable.getColumnModel().getColumnCount() > 0)
        {
            generalLoseTable.getColumnModel().getColumn(0).setResizable(false);
            generalLoseTable.getColumnModel().getColumn(1).setResizable(false);
        }

        thisWeekLabel.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        thisWeekLabel.setForeground(java.awt.Color.white);
        thisWeekLabel.setText("This weeks top");

        topHallLabel.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        topHallLabel.setForeground(java.awt.Color.white);
        topHallLabel.setText("Hall of Fame and Shame");

        allTimeLabel.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        allTimeLabel.setForeground(java.awt.Color.white);
        allTimeLabel.setText("Since The Begging Of Time");

        winsLabel.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        winsLabel.setForeground(java.awt.Color.white);
        winsLabel.setText("Wins");

        lossesLabel.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        lossesLabel.setForeground(java.awt.Color.white);
        lossesLabel.setText("Losses");

        youLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        youLabel1.setForeground(java.awt.Color.white);
        youLabel1.setText("You");

        userWeekWinsCounterLabel.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        userWeekWinsCounterLabel.setForeground(java.awt.Color.white);
        userWeekWinsCounterLabel.setText("0");

        userWeekLossesCounterLabel.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        userWeekLossesCounterLabel.setForeground(java.awt.Color.white);
        userWeekLossesCounterLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        userWeekLossesCounterLabel.setText("0");

        userEverWinsCounterLabel.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        userEverWinsCounterLabel.setForeground(java.awt.Color.white);
        userEverWinsCounterLabel.setText("0");

        youLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        youLabel2.setForeground(java.awt.Color.white);
        youLabel2.setText("You");

        userEverLossesCounterLabel.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        userEverLossesCounterLabel.setForeground(java.awt.Color.white);
        userEverLossesCounterLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        userEverLossesCounterLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(topHallLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(winsLabel)
                        .addGap(39, 39, 39)
                        .addComponent(thisWeekLabel)
                        .addGap(33, 33, 33)
                        .addComponent(lossesLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(userWeekWinsCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userWeekLossesCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(youLabel1)))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(allTimeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(youLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userEverWinsCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userEverLossesCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(topHallLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(winsLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(thisWeekLabel))
                    .addComponent(lossesLabel))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(youLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userWeekWinsCounterLabel)
                            .addComponent(userWeekLossesCounterLabel)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(allTimeLabel)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(youLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userEverWinsCounterLabel)
                            .addComponent(userEverLossesCounterLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allTimeLabel;
    private javax.swing.JTable generalLoseTable;
    private javax.swing.JTable generalWinTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lossesLabel;
    private javax.swing.JLabel thisWeekLabel;
    private javax.swing.JLabel topHallLabel;
    private javax.swing.JLabel userEverLossesCounterLabel;
    private javax.swing.JLabel userEverWinsCounterLabel;
    private javax.swing.JLabel userWeekLossesCounterLabel;
    private javax.swing.JLabel userWeekWinsCounterLabel;
    private javax.swing.JTable weekLoseTable;
    private javax.swing.JTable weekWinTable;
    private javax.swing.JLabel winsLabel;
    private javax.swing.JLabel youLabel1;
    private javax.swing.JLabel youLabel2;
    // End of variables declaration//GEN-END:variables
}
