/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.InteractionWithDB;
import Logic.Player;
import java.awt.Color;
import java.io.ObjectInputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;

/**
 *
 * @author Dizel
 */
public class LoginDialog extends javax.swing.JDialog
{

    /**
     * Creates new form LoginDialog
     */
    MainMenu parent;
    public LoginDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        
        this.parent = (MainMenu) parent;
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        loginText = new javax.swing.JLabel();
        loginInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginStatusLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setResizable(false);

        loginText.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        loginText.setForeground(new java.awt.Color(255, 255, 255));
        loginText.setText("Enter login");

        loginInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter password");

        loginButton.setBackground(java.awt.Color.lightGray);
        loginButton.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginButtonActionPerformed(evt);
            }
        });

        loginStatusLabel.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        loginStatusLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        passwordInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginInput)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(loginText))
                    .addComponent(passwordInput))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(loginText)
                .addGap(18, 18, 18)
                .addComponent(loginInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginButtonActionPerformed
    {//GEN-HEADEREND:event_loginButtonActionPerformed

        
            ObjectInputStream ois = null;
            Player player;
        try
        {
            player = new InteractionWithDB().getUser(loginInput.getText(), passwordInput.getText());
            if (player == null)
            {
                Thread notifyStatus = new Thread(new Runnable()
                {

                    @Override
                    public void run()
                    {
                        LoginDialog.this.loginStatusLabel.setText("Incorrect credentials");
                        LoginDialog.this.loginStatusLabel.repaint();
                        try
                        {
                            Thread.sleep(2000);
                            LoginDialog.this.loginStatusLabel.setText("");
                            LoginDialog.this.loginStatusLabel.repaint();
                        } catch (InterruptedException ex1)
                        {
                            Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    }
                    
                });
                notifyStatus.start();
            }
            else
            {
                player.setLoginToDatabase(loginInput.getText()); 
                new CharacterFrame(player).setVisible(true);
                parent.dispose();
                this.dispose();
            }
        } 
        
        catch (CommunicationsException ex)
        {
            
            
            Thread notifyStatus = new Thread(new Runnable()
                {

                    @Override
                    public void run()
                    {
                        LoginDialog.this.loginStatusLabel.setText("Server not responding");
                        LoginDialog.this.loginStatusLabel.repaint();
                        try
                        {
                            Thread.sleep(2000);
                            LoginDialog.this.loginStatusLabel.setText("");
                            LoginDialog.this.loginStatusLabel.repaint();
                        } catch (InterruptedException ex1)
                        {
                            Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    }
                    
                });
            notifyStatus.start();
        }
        
        catch (SQLException ex)
        {
            Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex);
        }             
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
         * @param args the command line arguments
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginInput;
    private javax.swing.JLabel loginStatusLabel;
    private javax.swing.JLabel loginText;
    private javax.swing.JPasswordField passwordInput;
    // End of variables declaration//GEN-END:variables
}
